export const SET_LOGIN_ERROR = 'LOGIN/ERROR';
export const LOGIN_ATTEMPT = 'LOGIN/TRY_LOGIN';
export const SHOW_LOGIN_SPINNER = 'LOGIN/SHOW_SPINNER';
export const HIDE_LOGIN_SPINNER = 'LOGIN/HIDE_SPINNER';
export const GET_STORES_LIST = 'LOGIN/GET_STORES_LIST';
export const SET_STORES_LIST = 'LOGIN/SET_STORES_LIST';